### ISSUE TITLE
SyntaxHighlighter 3.5.1 conflicts with the installed version of presenter

### ISSUE THREAD

**Issue by JonTheNiceGuy** [aaroncampbell/presenter#14]
SyntaxHighlighter upgraded from 3.5.0 to 3.5.1 last night, and I'm now getting this in my logs:

```
2019/10/09 09:24:41 [error] 18841#18841: *45326 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method SyntaxHighlighter::output_header_placeholder() in /var/www/critical_jon.sprig.gs/blog/wp-content/plugins/presenter/presenter.php:396
Stack trace:
#0 /var/www/critical_jon.sprig.gs/blog/wp-includes/class-wp-hook.php(286): presenter->head('')
#1 /var/www/critical_jon.sprig.gs/blog/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/critical_jon.sprig.gs/blog/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /var/www/critical_jon.sprig.gs/blog/wp-content/plugins/presenter/templates/header.php(20): do_action('presenter-head')
#4 /var/www/critical_jon.sprig.gs/blog/wp-content/plugins/presenter/templates/index.php(2): include('/var/www/critic...')
#5 /var/www/critical_jon.sprig.gs/blog/wp-includes/template-loader.php(78): include('/var/www/critic...')
#6 /var/www/critical_jon.sprig.gs/blog/wp-blog-header.php(19): require_once('/var/www/critic...')
```

Note that the line number for the presenter.php is slightly out, as I've added a tweak or two into the lines above, but this is the line in question:

```php
                        $SyntaxHighlighter->output_header_placeholder();
```

This has been fixed, for now, by disabling the syntax highlighter plugin!

I'll re-check with a clean environment when I'm not due to be giving my presentation in 1hr, but I wanted to log it now in case anyone else has encountered the same issue!

**Comment by aaroncampbell** [comment]
I just had this problem too, adding the `is_callable` fixed it for me
